//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptHelp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Anthony Duguid")]
        public string App_Author {
            get {
                return ((string)(this["App_Author"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBlue")]
        public global::System.Drawing.Color Table_ColumnCleanedColour {
            get {
                return ((global::System.Drawing.Color)(this["Table_ColumnCleanedColour"]));
            }
            set {
                this["Table_ColumnCleanedColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tbl")]
        public string Table_ColumnTableAlias {
            get {
                return ((string)(this["Table_ColumnTableAlias"]));
            }
            set {
                this["Table_ColumnTableAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Column_TypeDate {
            get {
                return ((int)(this["Column_TypeDate"]));
            }
            set {
                this["Column_TypeDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd-mmm-yyyy")]
        public string Table_ColumnFormatDate {
            get {
                return ((string)(this["Table_ColumnFormatDate"]));
            }
            set {
                this["Table_ColumnFormatDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("h:mm:ss AM/PM")]
        public string Table_ColumnFormatTime {
            get {
                return ((string)(this["Table_ColumnFormatTime"]));
            }
            set {
                this["Table_ColumnFormatTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NULL")]
        public string Table_ColumnScriptNull {
            get {
                return ((string)(this["Table_ColumnScriptNull"]));
            }
            set {
                this["Table_ColumnScriptNull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Column_TypeNumeric {
            get {
                return ((int)(this["Column_TypeNumeric"]));
            }
            set {
                this["Column_TypeNumeric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'")]
        public string Table_ColumnScriptQuote {
            get {
                return ((string)(this["Table_ColumnScriptQuote"]));
            }
            set {
                this["Table_ColumnScriptQuote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Column_TypeText {
            get {
                return ((int)(this["Column_TypeText"]));
            }
            set {
                this["Column_TypeText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Visible_grpClipboard {
            get {
                return ((bool)(this["Visible_grpClipboard"]));
            }
            set {
                this["Visible_grpClipboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SCRIPT")]
        public string Table_ColumnName {
            get {
                return ((string)(this["Table_ColumnName"]));
            }
            set {
                this["Table_ColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string Table_ColumnSeparateValuesDelimiter {
            get {
                return ((string)(this["Table_ColumnSeparateValuesDelimiter"]));
            }
            set {
                this["Table_ColumnSeparateValuesDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/Excel-projects/Script-Help/master/publish/")]
        public string App_PathDeploy {
            get {
                return ((string)(this["App_PathDeploy"]));
            }
            set {
                this["App_PathDeploy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_PathLocalData {
            get {
                return ((string)(this["App_PathLocalData"]));
            }
            set {
                this["App_PathLocalData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_mnuScriptType_DQL {
            get {
                return ((bool)(this["Visible_mnuScriptType_DQL"]));
            }
            set {
                this["Visible_mnuScriptType_DQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_mnuScriptType_TSQL {
            get {
                return ((bool)(this["Visible_mnuScriptType_TSQL"]));
            }
            set {
                this["Visible_mnuScriptType_TSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_mnuScriptType_PLSQL {
            get {
                return ((bool)(this["Visible_mnuScriptType_PLSQL"]));
            }
            set {
                this["Visible_mnuScriptType_PLSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_mnuScriptType_Markdown {
            get {
                return ((bool)(this["Visible_mnuScriptType_Markdown"]));
            }
            set {
                this["Visible_mnuScriptType_Markdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_mnuScriptType_Markup {
            get {
                return ((bool)(this["Visible_mnuScriptType_Markup"]));
            }
            set {
                this["Visible_mnuScriptType_Markup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Excel-projects/Script-Help/blob/master/README.md")]
        public string App_PathReadMe {
            get {
                return ((string)(this["App_PathReadMe"]));
            }
            set {
                this["App_PathReadMe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_PathDeployData {
            get {
                return ((string)(this["App_PathDeployData"]));
            }
            set {
                this["App_PathDeployData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TableStyleMedium15")]
        public string Table_StyleName {
            get {
                return ((string)(this["Table_StyleName"]));
            }
            set {
                this["Table_StyleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("07/31/2017 13:05:00")]
        public global::System.DateTime App_ReleaseDate {
            get {
                return ((global::System.DateTime)(this["App_ReleaseDate"]));
            }
            set {
                this["App_ReleaseDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Excel-projects/Script-Help/issues/new")]
        public string App_PathNewIssue {
            get {
                return ((string)(this["App_PathNewIssue"]));
            }
            set {
                this["App_PathNewIssue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Visible_grpAnnotation {
            get {
                return ((bool)(this["Visible_grpAnnotation"]));
            }
            set {
                this["Visible_grpAnnotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mm:ss.0")]
        public string Table_ColumnFormatDatePaste {
            get {
                return ((string)(this["Table_ColumnFormatDatePaste"]));
            }
            set {
                this["Table_ColumnFormatDatePaste"] = value;
            }
        }
    }
}
