//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptHelp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Anthony Duguid")]
        public string App_Author {
            get {
                return ((string)(this["App_Author"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBlue")]
        public global::System.Drawing.Color Sheet_ColumnCleanedColour {
            get {
                return ((global::System.Drawing.Color)(this["Sheet_ColumnCleanedColour"]));
            }
            set {
                this["Sheet_ColumnCleanedColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tbl")]
        public string Sheet_ColumnTableAlias {
            get {
                return ((string)(this["Sheet_ColumnTableAlias"]));
            }
            set {
                this["Sheet_ColumnTableAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Script_TypeDate {
            get {
                return ((int)(this["Script_TypeDate"]));
            }
            set {
                this["Script_TypeDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd-mmm-yyyy")]
        public string Sheet_ColumnDateFormatReplace {
            get {
                return ((string)(this["Sheet_ColumnDateFormatReplace"]));
            }
            set {
                this["Sheet_ColumnDateFormatReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mm:ss.0")]
        public string Sheet_ColumnDateFormatFind {
            get {
                return ((string)(this["Sheet_ColumnDateFormatFind"]));
            }
            set {
                this["Sheet_ColumnDateFormatFind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NULL")]
        public string Sheet_ColumnScriptNull {
            get {
                return ((string)(this["Sheet_ColumnScriptNull"]));
            }
            set {
                this["Sheet_ColumnScriptNull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Script_TypeNumeric {
            get {
                return ((int)(this["Script_TypeNumeric"]));
            }
            set {
                this["Script_TypeNumeric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'")]
        public string Sheet_ColumnScriptQuote {
            get {
                return ((string)(this["Sheet_ColumnScriptQuote"]));
            }
            set {
                this["Sheet_ColumnScriptQuote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Script_TypeText {
            get {
                return ((int)(this["Script_TypeText"]));
            }
            set {
                this["Script_TypeText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_ComAddInsDialog {
            get {
                return ((bool)(this["Visible_ComAddInsDialog"]));
            }
            set {
                this["Visible_ComAddInsDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_Options {
            get {
                return ((bool)(this["Visible_Options"]));
            }
            set {
                this["Visible_Options"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_FormatAsTableGallery {
            get {
                return ((bool)(this["Visible_FormatAsTableGallery"]));
            }
            set {
                this["Visible_FormatAsTableGallery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_RemoveDuplicates {
            get {
                return ((bool)(this["Visible_RemoveDuplicates"]));
            }
            set {
                this["Visible_RemoveDuplicates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_ViewFreezePanesGallery {
            get {
                return ((bool)(this["Visible_ViewFreezePanesGallery"]));
            }
            set {
                this["Visible_ViewFreezePanesGallery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_btnCopyVisibleCells {
            get {
                return ((bool)(this["Visible_btnCopyVisibleCells"]));
            }
            set {
                this["Visible_btnCopyVisibleCells"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_btnClearInteriorColor {
            get {
                return ((bool)(this["Visible_btnClearInteriorColor"]));
            }
            set {
                this["Visible_btnClearInteriorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_btnZeroToNull {
            get {
                return ((bool)(this["Visible_btnZeroToNull"]));
            }
            set {
                this["Visible_btnZeroToNull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp")]
        public string App_PathExport {
            get {
                return ((string)(this["App_PathExport"]));
            }
            set {
                this["App_PathExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Visible_btnFileList {
            get {
                return ((bool)(this["Visible_btnFileList"]));
            }
            set {
                this["Visible_btnFileList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Option_FileListingPathSelect {
            get {
                return ((bool)(this["Option_FileListingPathSelect"]));
            }
            set {
                this["Option_FileListingPathSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_mnuScriptType {
            get {
                return ((bool)(this["Visible_mnuScriptType"]));
            }
            set {
                this["Visible_mnuScriptType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SCRIPT")]
        public string Sheet_ColumnName {
            get {
                return ((string)(this["Sheet_ColumnName"]));
            }
            set {
                this["Sheet_ColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Visible_btnSeparateValues {
            get {
                return ((bool)(this["Visible_btnSeparateValues"]));
            }
            set {
                this["Visible_btnSeparateValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public char Sheet_ColumnSeparateValuesDelimiter {
            get {
                return ((char)(this["Sheet_ColumnSeparateValuesDelimiter"]));
            }
            set {
                this["Sheet_ColumnSeparateValuesDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/aduguid/ScriptHelp/master/publish/")]
        public string App_PathDeploy {
            get {
                return ((string)(this["App_PathDeploy"]));
            }
            set {
                this["App_PathDeploy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_PathLocalData {
            get {
                return ((string)(this["App_PathLocalData"]));
            }
            set {
                this["App_PathLocalData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_mnuScriptType_DQL {
            get {
                return ((bool)(this["Visible_mnuScriptType_DQL"]));
            }
            set {
                this["Visible_mnuScriptType_DQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_mnuScriptType_TSQL {
            get {
                return ((bool)(this["Visible_mnuScriptType_TSQL"]));
            }
            set {
                this["Visible_mnuScriptType_TSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_mnuScriptType_PLSQL {
            get {
                return ((bool)(this["Visible_mnuScriptType_PLSQL"]));
            }
            set {
                this["Visible_mnuScriptType_PLSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_mnuScriptType_Github {
            get {
                return ((bool)(this["Visible_mnuScriptType_Github"]));
            }
            set {
                this["Visible_mnuScriptType_Github"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_mnuScriptType_XML {
            get {
                return ((bool)(this["Visible_mnuScriptType_XML"]));
            }
            set {
                this["Visible_mnuScriptType_XML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/aduguid/ScriptHelp/blob/master/README.md")]
        public string App_PathReadMe {
            get {
                return ((string)(this["App_PathReadMe"]));
            }
            set {
                this["App_PathReadMe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_PathDeployData {
            get {
                return ((string)(this["App_PathDeployData"]));
            }
            set {
                this["App_PathDeployData"] = value;
            }
        }
    }
}
