//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptHelp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Anthony Duguid")]
        public string App_Author {
            get {
                return ((string)(this["App_Author"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBlue")]
        public global::System.Drawing.Color Sheet_Column_Cleaned_Colour {
            get {
                return ((global::System.Drawing.Color)(this["Sheet_Column_Cleaned_Colour"]));
            }
            set {
                this["Sheet_Column_Cleaned_Colour"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("anthonyduguid@gmail.com")]
        public string App_HelpEmail {
            get {
                return ((string)(this["App_HelpEmail"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tbl")]
        public string Sheet_Column_Table_Alias {
            get {
                return ((string)(this["Sheet_Column_Table_Alias"]));
            }
            set {
                this["Sheet_Column_Table_Alias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Script_Type_Date {
            get {
                return ((int)(this["Script_Type_Date"]));
            }
            set {
                this["Script_Type_Date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd-mmm-yyyy")]
        public string Sheet_Column_Date_Format_Replace {
            get {
                return ((string)(this["Sheet_Column_Date_Format_Replace"]));
            }
            set {
                this["Sheet_Column_Date_Format_Replace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mm:ss.0")]
        public string Sheet_Column_Date_Format_Find {
            get {
                return ((string)(this["Sheet_Column_Date_Format_Find"]));
            }
            set {
                this["Sheet_Column_Date_Format_Find"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NULL")]
        public string Sheet_Column_Script_Null {
            get {
                return ((string)(this["Sheet_Column_Script_Null"]));
            }
            set {
                this["Sheet_Column_Script_Null"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Script_Type_Numeric {
            get {
                return ((int)(this["Script_Type_Numeric"]));
            }
            set {
                this["Script_Type_Numeric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'")]
        public string Sheet_Column_Script_Quote {
            get {
                return ((string)(this["Sheet_Column_Script_Quote"]));
            }
            set {
                this["Sheet_Column_Script_Quote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Script_Type_Text {
            get {
                return ((int)(this["Script_Type_Text"]));
            }
            set {
                this["Script_Type_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_ComAddInsDialog {
            get {
                return ((bool)(this["Visible_ComAddInsDialog"]));
            }
            set {
                this["Visible_ComAddInsDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_Options {
            get {
                return ((bool)(this["Visible_Options"]));
            }
            set {
                this["Visible_Options"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_FormatAsTableGallery {
            get {
                return ((bool)(this["Visible_FormatAsTableGallery"]));
            }
            set {
                this["Visible_FormatAsTableGallery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_RemoveDuplicates {
            get {
                return ((bool)(this["Visible_RemoveDuplicates"]));
            }
            set {
                this["Visible_RemoveDuplicates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_ViewFreezePanesGallery {
            get {
                return ((bool)(this["Visible_ViewFreezePanesGallery"]));
            }
            set {
                this["Visible_ViewFreezePanesGallery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_btnCopyVisibleCells {
            get {
                return ((bool)(this["Visible_btnCopyVisibleCells"]));
            }
            set {
                this["Visible_btnCopyVisibleCells"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_btnClearInteriorColor {
            get {
                return ((bool)(this["Visible_btnClearInteriorColor"]));
            }
            set {
                this["Visible_btnClearInteriorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_btnZeroToNull {
            get {
                return ((bool)(this["Visible_btnZeroToNull"]));
            }
            set {
                this["Visible_btnZeroToNull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp")]
        public string App_PathFileListing {
            get {
                return ((string)(this["App_PathFileListing"]));
            }
            set {
                this["App_PathFileListing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Visible_btnFileList {
            get {
                return ((bool)(this["Visible_btnFileList"]));
            }
            set {
                this["Visible_btnFileList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Option_FileListingPathSelect {
            get {
                return ((bool)(this["Option_FileListingPathSelect"]));
            }
            set {
                this["Option_FileListingPathSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_mnuScriptType {
            get {
                return ((bool)(this["Visible_mnuScriptType"]));
            }
            set {
                this["Visible_mnuScriptType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QUERY")]
        public string Sheet_Column_Name {
            get {
                return ((string)(this["Sheet_Column_Name"]));
            }
            set {
                this["Sheet_Column_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Visible_btnSeparateValues {
            get {
                return ((bool)(this["Visible_btnSeparateValues"]));
            }
            set {
                this["Visible_btnSeparateValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public char Sheet_Column_Separate_Values_Delimiter {
            get {
                return ((char)(this["Sheet_Column_Separate_Values_Delimiter"]));
            }
            set {
                this["Sheet_Column_Separate_Values_Delimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\ScriptHelp")]
        public string App_PathDeploy {
            get {
                return ((string)(this["App_PathDeploy"]));
            }
            set {
                this["App_PathDeploy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_PathUserData {
            get {
                return ((string)(this["App_PathUserData"]));
            }
            set {
                this["App_PathUserData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Visible_mnuScriptType_DQL {
            get {
                return ((bool)(this["Visible_mnuScriptType_DQL"]));
            }
            set {
                this["Visible_mnuScriptType_DQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_mnuScriptType_TSQL {
            get {
                return ((bool)(this["Visible_mnuScriptType_TSQL"]));
            }
            set {
                this["Visible_mnuScriptType_TSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visible_mnuScriptType_PLSQL {
            get {
                return ((bool)(this["Visible_mnuScriptType_PLSQL"]));
            }
            set {
                this["Visible_mnuScriptType_PLSQL"] = value;
            }
        }
    }
}
