'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property Column_TypeText() As Integer
        Get
            Return CType(Me("Column_TypeText"),Integer)
        End Get
        Set
            Me("Column_TypeText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("'")>  _
    Public Property Table_ColumnScriptQuote() As String
        Get
            Return CType(Me("Table_ColumnScriptQuote"),String)
        End Get
        Set
            Me("Table_ColumnScriptQuote") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property Column_TypeNumeric() As Integer
        Get
            Return CType(Me("Column_TypeNumeric"),Integer)
        End Get
        Set
            Me("Column_TypeNumeric") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("NULL")>  _
    Public Property Table_ColumnScriptNull() As String
        Get
            Return CType(Me("Table_ColumnScriptNull"),String)
        End Get
        Set
            Me("Table_ColumnScriptNull") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("mm:ss.0")>  _
    Public Property Table_ColumnDateFormatFind() As String
        Get
            Return CType(Me("Table_ColumnDateFormatFind"),String)
        End Get
        Set
            Me("Table_ColumnDateFormatFind") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("dd-mmm-yyyy")>  _
    Public Property Table_ColumnDateFormatReplace() As String
        Get
            Return CType(Me("Table_ColumnDateFormatReplace"),String)
        End Get
        Set
            Me("Table_ColumnDateFormatReplace") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
    Public Property Column_TypeDate() As Integer
        Get
            Return CType(Me("Column_TypeDate"),Integer)
        End Get
        Set
            Me("Column_TypeDate") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SQL")>  _
    Public Property Table_ColumnName() As String
        Get
            Return CType(Me("Table_ColumnName"),String)
        End Get
        Set
            Me("Table_ColumnName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SkyBlue")>  _
    Public Property Table_ColumnCleanedColour() As Global.System.Drawing.Color
        Get
            Return CType(Me("Table_ColumnCleanedColour"),Global.System.Drawing.Color)
        End Get
        Set
            Me("Table_ColumnCleanedColour") = value
        End Set
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anthony Duguid")>  _
    Public ReadOnly Property App_Author() As String
        Get
            Return CType(Me("App_Author"),String)
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://github.com/aduguid/ScriptHelp/blob/master/README.md")>  _
    Public Property App_PathReadMe() As String
        Get
            Return CType(Me("App_PathReadMe"),String)
        End Get
        Set
            Me("App_PathReadMe") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Visible_grpFormatDataTable() As Boolean
        Get
            Return CType(Me("Visible_grpFormatDataTable"),Boolean)
        End Get
        Set
            Me("Visible_grpFormatDataTable") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/aduguid/ScriptHelp/master/publish/")>  _
    Public Property App_PathDeploy() As String
        Get
            Return CType(Me("App_PathDeploy"),String)
        End Get
        Set
            Me("App_PathDeploy") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property App_PathDeployData() As String
        Get
            Return CType(Me("App_PathDeployData"),String)
        End Get
        Set
            Me("App_PathDeployData") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\tduguid\Source\Repos\ScriptHelp2\VB\App_Data")>  _
    Public Property App_PathLocalData() As String
        Get
            Return CType(Me("App_PathLocalData"),String)
        End Get
        Set
            Me("App_PathLocalData") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://github.com/aduguid/ScriptHelp/issues/new")>  _
    Public Property App_PathReportIssue() As String
        Get
            Return CType(Me("App_PathReportIssue"),String)
        End Get
        Set
            Me("App_PathReportIssue") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("07/31/2017 13:05:00")>  _
    Public Property App_ReleaseDate() As Date
        Get
            Return CType(Me("App_ReleaseDate"),Date)
        End Get
        Set
            Me("App_ReleaseDate") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute(",")>  _
    Public Property Table_ColumnSeparateValuesDelimiter() As String
        Get
            Return CType(Me("Table_ColumnSeparateValuesDelimiter"),String)
        End Get
        Set
            Me("Table_ColumnSeparateValuesDelimiter") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tbl")>  _
    Public Property Table_ColumnTableAlias() As String
        Get
            Return CType(Me("Table_ColumnTableAlias"),String)
        End Get
        Set
            Me("Table_ColumnTableAlias") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("TableStyleMedium15")>  _
    Public Property Table_StyleName() As String
        Get
            Return CType(Me("Table_StyleName"),String)
        End Get
        Set
            Me("Table_StyleName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Visible_grpClipboard() As Boolean
        Get
            Return CType(Me("Visible_grpClipboard"),Boolean)
        End Get
        Set
            Me("Visible_grpClipboard") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Visible_grpScriptVariables() As Boolean
        Get
            Return CType(Me("Visible_grpScriptVariables"),Boolean)
        End Get
        Set
            Me("Visible_grpScriptVariables") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Visible_mnuScriptType() As Boolean
        Get
            Return CType(Me("Visible_mnuScriptType"),Boolean)
        End Get
        Set
            Me("Visible_mnuScriptType") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Visible_mnuScriptType_DQL() As Boolean
        Get
            Return CType(Me("Visible_mnuScriptType_DQL"),Boolean)
        End Get
        Set
            Me("Visible_mnuScriptType_DQL") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Visible_mnuScriptType_Github() As Boolean
        Get
            Return CType(Me("Visible_mnuScriptType_Github"),Boolean)
        End Get
        Set
            Me("Visible_mnuScriptType_Github") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Visible_mnuScriptType_PLSQL() As Boolean
        Get
            Return CType(Me("Visible_mnuScriptType_PLSQL"),Boolean)
        End Get
        Set
            Me("Visible_mnuScriptType_PLSQL") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Visible_mnuScriptType_TSQL() As Boolean
        Get
            Return CType(Me("Visible_mnuScriptType_TSQL"),Boolean)
        End Get
        Set
            Me("Visible_mnuScriptType_TSQL") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Visible_mnuScriptType_XML() As Boolean
        Get
            Return CType(Me("Visible_mnuScriptType_XML"),Boolean)
        End Get
        Set
            Me("Visible_mnuScriptType_XML") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Visible_btnSeparateValues() As Boolean
        Get
            Return CType(Me("Visible_btnSeparateValues"),Boolean)
        End Get
        Set
            Me("Visible_btnSeparateValues") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Visible_btnZeroToNull() As Boolean
        Get
            Return CType(Me("Visible_btnZeroToNull"),Boolean)
        End Get
        Set
            Me("Visible_btnZeroToNull") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\Temp")>  _
    Public Property Option_PathFileListing() As String
        Get
            Return CType(Me("Option_PathFileListing"),String)
        End Get
        Set
            Me("Option_PathFileListing") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Option_PathFileListingSelect() As Boolean
        Get
            Return CType(Me("Option_PathFileListingSelect"),Boolean)
        End Get
        Set
            Me("Option_PathFileListingSelect") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Visible_btnClearInteriorColor() As Boolean
        Get
            Return CType(Me("Visible_btnClearInteriorColor"),Boolean)
        End Get
        Set
            Me("Visible_btnClearInteriorColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Visible_btnFileList() As Boolean
        Get
            Return CType(Me("Visible_btnFileList"),Boolean)
        End Get
        Set
            Me("Visible_btnFileList") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ScriptHelp.MySettings
            Get
                Return Global.ScriptHelp.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
